spring:
  profiles:
    active: dev
  application:
    name: taxi-eljanoub
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8080

logging:
  level:
    root: INFO
    com.taxi.eljanoub: DEBUG
